language: ruby
rvm:
  - 2.4.2

before_install:
  - TFVERSION=0.11.8 bash -c 'curl -L "https://releases.hashicorp.com/terraform/${TFVERSION}/terraform_${TFVERSION}_linux_amd64.zip" -o /tmp/terraform.zip'
  - sudo unzip -d /usr/local/bin/ /tmp/terraform.zip
  - sudo chmod +x /usr/local/bin/terraform
  - TFDOCSVERSION=0.4.0 bash -c 'curl -L "https://github.com/segmentio/terraform-docs/releases/download/v${TFDOCSVERSION}/terraform-docs-v${TFDOCSVERSION}-linux-amd64" -o /usr/local/bin/terraform-docs'
  - sudo chmod +x /usr/local/bin/terraform-docs
  - sudo apt-get update && sudo apt-get install -y python-pip

sudo: required

env:
  - MAKE_TASK=lint

script:
  - make $MAKE_TASK
