language: ruby
rvm:
  - 2.4.2

before_install:
  - TFVERSION=0.11.8 bash -c 'curl -L "https://releases.hashicorp.com/terraform/${TFVERSION}/terraform_${TFVERSION}_linux_amd64.zip" -o /tmp/terraform.zip'
  - sudo unzip -d /usr/local/bin/ /tmp/terraform.zip
  - sudo chmod +x /usr/local/bin/terraform
  - sudo apt-get update && apt-get install -y python-pip

sudo: required

env:
  - MAKE_TASK=lint

script:
  - make $MAKE_TASK
